// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amber-java-common/src/main/resources/drivermsg.proto

package pl.edu.agh.amber.common.proto;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code amber.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NINEDOF = 1;</code>
     */
    NINEDOF(0, 1),
    /**
     * <code>ROBOCLAW = 2;</code>
     */
    ROBOCLAW(1, 2),
    /**
     * <code>STARGAZER = 3;</code>
     */
    STARGAZER(2, 3),
    /**
     * <code>HOKUYO = 4;</code>
     */
    HOKUYO(3, 4),
    /**
     * <code>DUMMY = 5;</code>
     */
    DUMMY(4, 5),
    /**
     * <code>LOCATION = 6;</code>
     */
    LOCATION(5, 6),
    /**
     * <code>MAESTRO = 7;</code>
     */
    MAESTRO(6, 7),
    /**
     * <code>DRIVE_TO_POINT = 8;</code>
     */
    DRIVE_TO_POINT(7, 8),
    /**
     * <code>COLLISION_AVOIDANCE = 9;</code>
     */
    COLLISION_AVOIDANCE(8, 9),
    /**
     * <code>PID_FOLLOW_TRAJECTORY = 10;</code>
     */
    PID_FOLLOW_TRAJECTORY(9, 10),
    ;

    /**
     * <code>NINEDOF = 1;</code>
     */
    public static final int NINEDOF_VALUE = 1;
    /**
     * <code>ROBOCLAW = 2;</code>
     */
    public static final int ROBOCLAW_VALUE = 2;
    /**
     * <code>STARGAZER = 3;</code>
     */
    public static final int STARGAZER_VALUE = 3;
    /**
     * <code>HOKUYO = 4;</code>
     */
    public static final int HOKUYO_VALUE = 4;
    /**
     * <code>DUMMY = 5;</code>
     */
    public static final int DUMMY_VALUE = 5;
    /**
     * <code>LOCATION = 6;</code>
     */
    public static final int LOCATION_VALUE = 6;
    /**
     * <code>MAESTRO = 7;</code>
     */
    public static final int MAESTRO_VALUE = 7;
    /**
     * <code>DRIVE_TO_POINT = 8;</code>
     */
    public static final int DRIVE_TO_POINT_VALUE = 8;
    /**
     * <code>COLLISION_AVOIDANCE = 9;</code>
     */
    public static final int COLLISION_AVOIDANCE_VALUE = 9;
    /**
     * <code>PID_FOLLOW_TRAJECTORY = 10;</code>
     */
    public static final int PID_FOLLOW_TRAJECTORY_VALUE = 10;


    public final int getNumber() { return value; }

    public static DeviceType valueOf(int value) {
      switch (value) {
        case 1: return NINEDOF;
        case 2: return ROBOCLAW;
        case 3: return STARGAZER;
        case 4: return HOKUYO;
        case 5: return DUMMY;
        case 6: return LOCATION;
        case 7: return MAESTRO;
        case 8: return DRIVE_TO_POINT;
        case 9: return COLLISION_AVOIDANCE;
        case 10: return PID_FOLLOW_TRAJECTORY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pl.edu.agh.amber.common.proto.CommonProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:amber.DeviceType)
  }

  public interface DriverHdrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.DriverHdr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    int getDeviceType();

    /**
     * <code>optional int32 deviceID = 2;</code>
     */
    boolean hasDeviceID();
    /**
     * <code>optional int32 deviceID = 2;</code>
     */
    int getDeviceID();

    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getClientIDsList();
    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    int getClientIDsCount();
    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    int getClientIDs(int index);
  }
  /**
   * Protobuf type {@code amber.DriverHdr}
   */
  public static final class DriverHdr extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:amber.DriverHdr)
      DriverHdrOrBuilder {
    // Use DriverHdr.newBuilder() to construct.
    private DriverHdr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DriverHdr(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DriverHdr defaultInstance;
    public static DriverHdr getDefaultInstance() {
      return defaultInstance;
    }

    public DriverHdr getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DriverHdr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deviceID_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                clientIDs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              clientIDs_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                clientIDs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                clientIDs_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          clientIDs_ = java.util.Collections.unmodifiableList(clientIDs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverHdr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverHdr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.class, pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.Builder.class);
    }

    public static com.google.protobuf.Parser<DriverHdr> PARSER =
        new com.google.protobuf.AbstractParser<DriverHdr>() {
      public DriverHdr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DriverHdr(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DriverHdr> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 deviceType = 1;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    private int deviceID_;
    /**
     * <code>optional int32 deviceID = 2;</code>
     */
    public boolean hasDeviceID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 deviceID = 2;</code>
     */
    public int getDeviceID() {
      return deviceID_;
    }

    public static final int CLIENTIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> clientIDs_;
    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getClientIDsList() {
      return clientIDs_;
    }
    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    public int getClientIDsCount() {
      return clientIDs_.size();
    }
    /**
     * <code>repeated int32 clientIDs = 3 [packed = true];</code>
     */
    public int getClientIDs(int index) {
      return clientIDs_.get(index);
    }
    private int clientIDsMemoizedSerializedSize = -1;

    private void initFields() {
      deviceType_ = 0;
      deviceID_ = 0;
      clientIDs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, deviceID_);
      }
      if (getClientIDsList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(clientIDsMemoizedSerializedSize);
      }
      for (int i = 0; i < clientIDs_.size(); i++) {
        output.writeInt32NoTag(clientIDs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, deviceID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clientIDs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(clientIDs_.get(i));
        }
        size += dataSize;
        if (!getClientIDsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        clientIDsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.common.proto.CommonProto.DriverHdr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.DriverHdr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.DriverHdr)
        pl.edu.agh.amber.common.proto.CommonProto.DriverHdrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverHdr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverHdr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.class, pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.Builder.class);
      }

      // Construct using pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientIDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverHdr_descriptor;
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverHdr getDefaultInstanceForType() {
        return pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.getDefaultInstance();
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverHdr build() {
        pl.edu.agh.amber.common.proto.CommonProto.DriverHdr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverHdr buildPartial() {
        pl.edu.agh.amber.common.proto.CommonProto.DriverHdr result = new pl.edu.agh.amber.common.proto.CommonProto.DriverHdr(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceID_ = deviceID_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          clientIDs_ = java.util.Collections.unmodifiableList(clientIDs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.clientIDs_ = clientIDs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.common.proto.CommonProto.DriverHdr) {
          return mergeFrom((pl.edu.agh.amber.common.proto.CommonProto.DriverHdr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.common.proto.CommonProto.DriverHdr other) {
        if (other == pl.edu.agh.amber.common.proto.CommonProto.DriverHdr.getDefaultInstance()) return this;
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasDeviceID()) {
          setDeviceID(other.getDeviceID());
        }
        if (!other.clientIDs_.isEmpty()) {
          if (clientIDs_.isEmpty()) {
            clientIDs_ = other.clientIDs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClientIDsIsMutable();
            clientIDs_.addAll(other.clientIDs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.common.proto.CommonProto.DriverHdr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.common.proto.CommonProto.DriverHdr) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int deviceType_ ;
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder setDeviceType(int value) {
        bitField0_ |= 0x00000001;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 deviceType = 1;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceType_ = 0;
        onChanged();
        return this;
      }

      private int deviceID_ ;
      /**
       * <code>optional int32 deviceID = 2;</code>
       */
      public boolean hasDeviceID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 deviceID = 2;</code>
       */
      public int getDeviceID() {
        return deviceID_;
      }
      /**
       * <code>optional int32 deviceID = 2;</code>
       */
      public Builder setDeviceID(int value) {
        bitField0_ |= 0x00000002;
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 deviceID = 2;</code>
       */
      public Builder clearDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceID_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> clientIDs_ = java.util.Collections.emptyList();
      private void ensureClientIDsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          clientIDs_ = new java.util.ArrayList<java.lang.Integer>(clientIDs_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getClientIDsList() {
        return java.util.Collections.unmodifiableList(clientIDs_);
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public int getClientIDsCount() {
        return clientIDs_.size();
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public int getClientIDs(int index) {
        return clientIDs_.get(index);
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public Builder setClientIDs(
          int index, int value) {
        ensureClientIDsIsMutable();
        clientIDs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public Builder addClientIDs(int value) {
        ensureClientIDsIsMutable();
        clientIDs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public Builder addAllClientIDs(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureClientIDsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, clientIDs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 clientIDs = 3 [packed = true];</code>
       */
      public Builder clearClientIDs() {
        clientIDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.DriverHdr)
    }

    static {
      defaultInstance = new DriverHdr(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.DriverHdr)
  }

  public interface DriverMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.DriverMsg)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<DriverMsg> {

    /**
     * <code>required .amber.DriverMsg.MsgType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .amber.DriverMsg.MsgType type = 2;</code>
     */
    pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType getType();

    /**
     * <code>optional uint32 synNum = 3;</code>
     */
    boolean hasSynNum();
    /**
     * <code>optional uint32 synNum = 3;</code>
     */
    int getSynNum();

    /**
     * <code>optional uint32 ackNum = 4;</code>
     */
    boolean hasAckNum();
    /**
     * <code>optional uint32 ackNum = 4;</code>
     */
    int getAckNum();

    /**
     * <code>optional uint32 listenerNum = 5;</code>
     */
    boolean hasListenerNum();
    /**
     * <code>optional uint32 listenerNum = 5;</code>
     */
    int getListenerNum();
  }
  /**
   * Protobuf type {@code amber.DriverMsg}
   */
  public static final class DriverMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        DriverMsg> implements
      // @@protoc_insertion_point(message_implements:amber.DriverMsg)
      DriverMsgOrBuilder {
    // Use DriverMsg.newBuilder() to construct.
    private DriverMsg(com.google.protobuf.GeneratedMessage.ExtendableBuilder<pl.edu.agh.amber.common.proto.CommonProto.DriverMsg, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DriverMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DriverMsg defaultInstance;
    public static DriverMsg getDefaultInstance() {
      return defaultInstance;
    }

    public DriverMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DriverMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType value = pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              synNum_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              ackNum_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              listenerNum_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.class, pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<DriverMsg> PARSER =
        new com.google.protobuf.AbstractParser<DriverMsg>() {
      public DriverMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DriverMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DriverMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code amber.DriverMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATA = 1;</code>
       */
      DATA(0, 1),
      /**
       * <code>PING = 2;</code>
       */
      PING(1, 2),
      /**
       * <code>PONG = 3;</code>
       */
      PONG(2, 3),
      /**
       * <code>CLIENT_DIED = 4;</code>
       */
      CLIENT_DIED(3, 4),
      /**
       * <code>DRIVER_DIED = 5;</code>
       */
      DRIVER_DIED(4, 5),
      /**
       * <code>SUBSCRIBE = 6;</code>
       */
      SUBSCRIBE(5, 6),
      /**
       * <code>UNSUBSCRIBE = 7;</code>
       */
      UNSUBSCRIBE(6, 7),
      ;

      /**
       * <code>DATA = 1;</code>
       */
      public static final int DATA_VALUE = 1;
      /**
       * <code>PING = 2;</code>
       */
      public static final int PING_VALUE = 2;
      /**
       * <code>PONG = 3;</code>
       */
      public static final int PONG_VALUE = 3;
      /**
       * <code>CLIENT_DIED = 4;</code>
       */
      public static final int CLIENT_DIED_VALUE = 4;
      /**
       * <code>DRIVER_DIED = 5;</code>
       */
      public static final int DRIVER_DIED_VALUE = 5;
      /**
       * <code>SUBSCRIBE = 6;</code>
       */
      public static final int SUBSCRIBE_VALUE = 6;
      /**
       * <code>UNSUBSCRIBE = 7;</code>
       */
      public static final int UNSUBSCRIBE_VALUE = 7;


      public final int getNumber() { return value; }

      public static MsgType valueOf(int value) {
        switch (value) {
          case 1: return DATA;
          case 2: return PING;
          case 3: return PONG;
          case 4: return CLIENT_DIED;
          case 5: return DRIVER_DIED;
          case 6: return SUBSCRIBE;
          case 7: return UNSUBSCRIBE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:amber.DriverMsg.MsgType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 2;
    private pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType type_;
    /**
     * <code>required .amber.DriverMsg.MsgType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .amber.DriverMsg.MsgType type = 2;</code>
     */
    public pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType getType() {
      return type_;
    }

    public static final int SYNNUM_FIELD_NUMBER = 3;
    private int synNum_;
    /**
     * <code>optional uint32 synNum = 3;</code>
     */
    public boolean hasSynNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 synNum = 3;</code>
     */
    public int getSynNum() {
      return synNum_;
    }

    public static final int ACKNUM_FIELD_NUMBER = 4;
    private int ackNum_;
    /**
     * <code>optional uint32 ackNum = 4;</code>
     */
    public boolean hasAckNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 ackNum = 4;</code>
     */
    public int getAckNum() {
      return ackNum_;
    }

    public static final int LISTENERNUM_FIELD_NUMBER = 5;
    private int listenerNum_;
    /**
     * <code>optional uint32 listenerNum = 5;</code>
     */
    public boolean hasListenerNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 listenerNum = 5;</code>
     */
    public int getListenerNum() {
      return listenerNum_;
    }

    private void initFields() {
      type_ = pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType.DATA;
      synNum_ = 0;
      ackNum_ = 0;
      listenerNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<pl.edu.agh.amber.common.proto.CommonProto.DriverMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(3, synNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, ackNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, listenerNum_);
      }
      extensionWriter.writeUntil(200, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, synNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ackNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, listenerNum_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.common.proto.CommonProto.DriverMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.DriverMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          pl.edu.agh.amber.common.proto.CommonProto.DriverMsg, Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.DriverMsg)
        pl.edu.agh.amber.common.proto.CommonProto.DriverMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.class, pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.Builder.class);
      }

      // Construct using pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType.DATA;
        bitField0_ = (bitField0_ & ~0x00000001);
        synNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ackNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        listenerNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.common.proto.CommonProto.internal_static_amber_DriverMsg_descriptor;
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverMsg getDefaultInstanceForType() {
        return pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.getDefaultInstance();
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverMsg build() {
        pl.edu.agh.amber.common.proto.CommonProto.DriverMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.common.proto.CommonProto.DriverMsg buildPartial() {
        pl.edu.agh.amber.common.proto.CommonProto.DriverMsg result = new pl.edu.agh.amber.common.proto.CommonProto.DriverMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.synNum_ = synNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ackNum_ = ackNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.listenerNum_ = listenerNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.common.proto.CommonProto.DriverMsg) {
          return mergeFrom((pl.edu.agh.amber.common.proto.CommonProto.DriverMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.common.proto.CommonProto.DriverMsg other) {
        if (other == pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSynNum()) {
          setSynNum(other.getSynNum());
        }
        if (other.hasAckNum()) {
          setAckNum(other.getAckNum());
        }
        if (other.hasListenerNum()) {
          setListenerNum(other.getListenerNum());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.common.proto.CommonProto.DriverMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.common.proto.CommonProto.DriverMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType type_ = pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType.DATA;
      /**
       * <code>required .amber.DriverMsg.MsgType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .amber.DriverMsg.MsgType type = 2;</code>
       */
      public pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType getType() {
        return type_;
      }
      /**
       * <code>required .amber.DriverMsg.MsgType type = 2;</code>
       */
      public Builder setType(pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .amber.DriverMsg.MsgType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = pl.edu.agh.amber.common.proto.CommonProto.DriverMsg.MsgType.DATA;
        onChanged();
        return this;
      }

      private int synNum_ ;
      /**
       * <code>optional uint32 synNum = 3;</code>
       */
      public boolean hasSynNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 synNum = 3;</code>
       */
      public int getSynNum() {
        return synNum_;
      }
      /**
       * <code>optional uint32 synNum = 3;</code>
       */
      public Builder setSynNum(int value) {
        bitField0_ |= 0x00000002;
        synNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 synNum = 3;</code>
       */
      public Builder clearSynNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        synNum_ = 0;
        onChanged();
        return this;
      }

      private int ackNum_ ;
      /**
       * <code>optional uint32 ackNum = 4;</code>
       */
      public boolean hasAckNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 ackNum = 4;</code>
       */
      public int getAckNum() {
        return ackNum_;
      }
      /**
       * <code>optional uint32 ackNum = 4;</code>
       */
      public Builder setAckNum(int value) {
        bitField0_ |= 0x00000004;
        ackNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 ackNum = 4;</code>
       */
      public Builder clearAckNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ackNum_ = 0;
        onChanged();
        return this;
      }

      private int listenerNum_ ;
      /**
       * <code>optional uint32 listenerNum = 5;</code>
       */
      public boolean hasListenerNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 listenerNum = 5;</code>
       */
      public int getListenerNum() {
        return listenerNum_;
      }
      /**
       * <code>optional uint32 listenerNum = 5;</code>
       */
      public Builder setListenerNum(int value) {
        bitField0_ |= 0x00000008;
        listenerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 listenerNum = 5;</code>
       */
      public Builder clearListenerNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        listenerNum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.DriverMsg)
    }

    static {
      defaultInstance = new DriverMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.DriverMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_DriverHdr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_DriverHdr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_DriverMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_DriverMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4amber-java-common/src/main/resources/d" +
      "rivermsg.proto\022\005amber\"H\n\tDriverHdr\022\022\n\nde" +
      "viceType\030\001 \001(\005\022\020\n\010deviceID\030\002 \001(\005\022\025\n\tclie" +
      "ntIDs\030\003 \003(\005B\002\020\001\"\332\001\n\tDriverMsg\022&\n\004type\030\002 " +
      "\002(\0162\030.amber.DriverMsg.MsgType\022\016\n\006synNum\030" +
      "\003 \001(\r\022\016\n\006ackNum\030\004 \001(\r\022\023\n\013listenerNum\030\005 \001" +
      "(\r\"i\n\007MsgType\022\010\n\004DATA\020\001\022\010\n\004PING\020\002\022\010\n\004PON" +
      "G\020\003\022\017\n\013CLIENT_DIED\020\004\022\017\n\013DRIVER_DIED\020\005\022\r\n" +
      "\tSUBSCRIBE\020\006\022\017\n\013UNSUBSCRIBE\020\007*\005\010\n\020\310\001*\260\001\n" +
      "\nDeviceType\022\013\n\007NINEDOF\020\001\022\014\n\010ROBOCLAW\020\002\022\r",
      "\n\tSTARGAZER\020\003\022\n\n\006HOKUYO\020\004\022\t\n\005DUMMY\020\005\022\014\n\010" +
      "LOCATION\020\006\022\013\n\007MAESTRO\020\007\022\022\n\016DRIVE_TO_POIN" +
      "T\020\010\022\027\n\023COLLISION_AVOIDANCE\020\t\022\031\n\025PID_FOLL" +
      "OW_TRAJECTORY\020\nB.\n\035pl.edu.agh.amber.comm" +
      "on.protoB\013CommonProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_amber_DriverHdr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amber_DriverHdr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_DriverHdr_descriptor,
        new java.lang.String[] { "DeviceType", "DeviceID", "ClientIDs", });
    internal_static_amber_DriverMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amber_DriverMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_DriverMsg_descriptor,
        new java.lang.String[] { "Type", "SynNum", "AckNum", "ListenerNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
