// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hokuyo.proto

package pl.edu.agh.amber.hokuyo.proto;

public final class HokuyoProto {
  private HokuyoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(pl.edu.agh.amber.hokuyo.proto.HokuyoProto.getSingleScan);
    registry.add(pl.edu.agh.amber.hokuyo.proto.HokuyoProto.scan);
    registry.add(pl.edu.agh.amber.hokuyo.proto.HokuyoProto.timestamp);
  }
  public interface ScanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated double angles = 1 [packed = true];
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getAnglesList();
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    int getAnglesCount();
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    double getAngles(int index);

    // repeated int32 distances = 2 [packed = true];
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getDistancesList();
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    int getDistancesCount();
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    int getDistances(int index);
  }
  /**
   * Protobuf type {@code amber.hokuyo_proto.Scan}
   */
  public static final class Scan extends
      com.google.protobuf.GeneratedMessage
      implements ScanOrBuilder {
    // Use Scan.newBuilder() to construct.
    private Scan(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Scan(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Scan defaultInstance;
    public static Scan getDefaultInstance() {
      return defaultInstance;
    }

    public Scan getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Scan(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                angles_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              angles_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                angles_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                angles_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                distances_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              distances_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                distances_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                distances_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          angles_ = java.util.Collections.unmodifiableList(angles_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          distances_ = java.util.Collections.unmodifiableList(distances_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.internal_static_amber_hokuyo_proto_Scan_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.internal_static_amber_hokuyo_proto_Scan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.class, pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.Builder.class);
    }

    public static com.google.protobuf.Parser<Scan> PARSER =
        new com.google.protobuf.AbstractParser<Scan>() {
      public Scan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Scan(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Scan> getParserForType() {
      return PARSER;
    }

    // repeated double angles = 1 [packed = true];
    public static final int ANGLES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> angles_;
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getAnglesList() {
      return angles_;
    }
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    public int getAnglesCount() {
      return angles_.size();
    }
    /**
     * <code>repeated double angles = 1 [packed = true];</code>
     */
    public double getAngles(int index) {
      return angles_.get(index);
    }
    private int anglesMemoizedSerializedSize = -1;

    // repeated int32 distances = 2 [packed = true];
    public static final int DISTANCES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> distances_;
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getDistancesList() {
      return distances_;
    }
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    public int getDistancesCount() {
      return distances_.size();
    }
    /**
     * <code>repeated int32 distances = 2 [packed = true];</code>
     */
    public int getDistances(int index) {
      return distances_.get(index);
    }
    private int distancesMemoizedSerializedSize = -1;

    private void initFields() {
      angles_ = java.util.Collections.emptyList();
      distances_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getAnglesList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(anglesMemoizedSerializedSize);
      }
      for (int i = 0; i < angles_.size(); i++) {
        output.writeDoubleNoTag(angles_.get(i));
      }
      if (getDistancesList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(distancesMemoizedSerializedSize);
      }
      for (int i = 0; i < distances_.size(); i++) {
        output.writeInt32NoTag(distances_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getAnglesList().size();
        size += dataSize;
        if (!getAnglesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        anglesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < distances_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(distances_.get(i));
        }
        size += dataSize;
        if (!getDistancesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        distancesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.hokuyo_proto.Scan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.hokuyo.proto.HokuyoProto.ScanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.internal_static_amber_hokuyo_proto_Scan_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.internal_static_amber_hokuyo_proto_Scan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.class, pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.Builder.class);
      }

      // Construct using pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        angles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        distances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.internal_static_amber_hokuyo_proto_Scan_descriptor;
      }

      public pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan getDefaultInstanceForType() {
        return pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.getDefaultInstance();
      }

      public pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan build() {
        pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan buildPartial() {
        pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan result = new pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          angles_ = java.util.Collections.unmodifiableList(angles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.angles_ = angles_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          distances_ = java.util.Collections.unmodifiableList(distances_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.distances_ = distances_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan) {
          return mergeFrom((pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan other) {
        if (other == pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.getDefaultInstance()) return this;
        if (!other.angles_.isEmpty()) {
          if (angles_.isEmpty()) {
            angles_ = other.angles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnglesIsMutable();
            angles_.addAll(other.angles_);
          }
          onChanged();
        }
        if (!other.distances_.isEmpty()) {
          if (distances_.isEmpty()) {
            distances_ = other.distances_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDistancesIsMutable();
            distances_.addAll(other.distances_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated double angles = 1 [packed = true];
      private java.util.List<java.lang.Double> angles_ = java.util.Collections.emptyList();
      private void ensureAnglesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          angles_ = new java.util.ArrayList<java.lang.Double>(angles_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getAnglesList() {
        return java.util.Collections.unmodifiableList(angles_);
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public int getAnglesCount() {
        return angles_.size();
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public double getAngles(int index) {
        return angles_.get(index);
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public Builder setAngles(
          int index, double value) {
        ensureAnglesIsMutable();
        angles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public Builder addAngles(double value) {
        ensureAnglesIsMutable();
        angles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public Builder addAllAngles(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureAnglesIsMutable();
        super.addAll(values, angles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 1 [packed = true];</code>
       */
      public Builder clearAngles() {
        angles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated int32 distances = 2 [packed = true];
      private java.util.List<java.lang.Integer> distances_ = java.util.Collections.emptyList();
      private void ensureDistancesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          distances_ = new java.util.ArrayList<java.lang.Integer>(distances_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getDistancesList() {
        return java.util.Collections.unmodifiableList(distances_);
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public int getDistancesCount() {
        return distances_.size();
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public int getDistances(int index) {
        return distances_.get(index);
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public Builder setDistances(
          int index, int value) {
        ensureDistancesIsMutable();
        distances_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public Builder addDistances(int value) {
        ensureDistancesIsMutable();
        distances_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public Builder addAllDistances(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDistancesIsMutable();
        super.addAll(values, distances_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 distances = 2 [packed = true];</code>
       */
      public Builder clearDistances() {
        distances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.hokuyo_proto.Scan)
    }

    static {
      defaultInstance = new Scan(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.hokuyo_proto.Scan)
  }

  public static final int GET_SINGLE_SCAN_FIELD_NUMBER = 40;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> getSingleScan = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SCAN_FIELD_NUMBER = 41;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan> scan = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.class,
        pl.edu.agh.amber.hokuyo.proto.HokuyoProto.Scan.getDefaultInstance());
  public static final int TIMESTAMP_FIELD_NUMBER = 49;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Long> timestamp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_hokuyo_proto_Scan_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_hokuyo_proto_Scan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014hokuyo.proto\022\022amber.hokuyo_proto\032\017driv" +
      "ermsg.proto\"1\n\004Scan\022\022\n\006angles\030\001 \003(\001B\002\020\001\022" +
      "\025\n\tdistances\030\002 \003(\005B\002\020\001:)\n\017get_single_sca" +
      "n\022\020.amber.DriverMsg\030( \001(\010:8\n\004scan\022\020.ambe" +
      "r.DriverMsg\030) \001(\0132\030.amber.hokuyo_proto.S" +
      "can:#\n\ttimestamp\022\020.amber.DriverMsg\0301 \001(\003" +
      "B,\n\035pl.edu.agh.amber.hokuyo.protoB\013Hokuy" +
      "oProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_hokuyo_proto_Scan_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_hokuyo_proto_Scan_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_hokuyo_proto_Scan_descriptor,
              new java.lang.String[] { "Angles", "Distances", });
          getSingleScan.internalInit(descriptor.getExtensions().get(0));
          scan.internalInit(descriptor.getExtensions().get(1));
          timestamp.internalInit(descriptor.getExtensions().get(2));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.agh.amber.common.proto.CommonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
