// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/hitec.proto

package pl.edu.agh.amber.hitec.proto;

public final class HitecProto {
  private HitecProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(pl.edu.agh.amber.hitec.proto.HitecProto.setAngleCommand);
    registry.add(pl.edu.agh.amber.hitec.proto.HitecProto.setSameAngleCommand);
    registry.add(pl.edu.agh.amber.hitec.proto.HitecProto.setDifferentAnglesCommand);
    registry.add(pl.edu.agh.amber.hitec.proto.HitecProto.setSpeedCommand);
  }
  public interface SetAngleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.hitec_proto.SetAngle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    boolean hasServoAddress();
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    int getServoAddress();

    /**
     * <code>required int32 angle = 2;</code>
     */
    boolean hasAngle();
    /**
     * <code>required int32 angle = 2;</code>
     */
    int getAngle();
  }
  /**
   * Protobuf type {@code amber.hitec_proto.SetAngle}
   */
  public static final class SetAngle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:amber.hitec_proto.SetAngle)
      SetAngleOrBuilder {
    // Use SetAngle.newBuilder() to construct.
    private SetAngle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetAngle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetAngle defaultInstance;
    public static SetAngle getDefaultInstance() {
      return defaultInstance;
    }

    public SetAngle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetAngle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              servoAddress_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              angle_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetAngle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetAngle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.Builder.class);
    }

    public static com.google.protobuf.Parser<SetAngle> PARSER =
        new com.google.protobuf.AbstractParser<SetAngle>() {
      public SetAngle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetAngle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetAngle> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVOADDRESS_FIELD_NUMBER = 1;
    private int servoAddress_;
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    public boolean hasServoAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    public int getServoAddress() {
      return servoAddress_;
    }

    public static final int ANGLE_FIELD_NUMBER = 2;
    private int angle_;
    /**
     * <code>required int32 angle = 2;</code>
     */
    public boolean hasAngle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 angle = 2;</code>
     */
    public int getAngle() {
      return angle_;
    }

    private void initFields() {
      servoAddress_ = 0;
      angle_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServoAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAngle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, servoAddress_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, angle_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, servoAddress_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, angle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.hitec_proto.SetAngle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.hitec_proto.SetAngle)
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetAngle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetAngle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.Builder.class);
      }

      // Construct using pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servoAddress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        angle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetAngle_descriptor;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle getDefaultInstanceForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.getDefaultInstance();
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle build() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle buildPartial() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle result = new pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.servoAddress_ = servoAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.angle_ = angle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle) {
          return mergeFrom((pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle other) {
        if (other == pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.getDefaultInstance()) return this;
        if (other.hasServoAddress()) {
          setServoAddress(other.getServoAddress());
        }
        if (other.hasAngle()) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServoAddress()) {
          
          return false;
        }
        if (!hasAngle()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int servoAddress_ ;
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public boolean hasServoAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public int getServoAddress() {
        return servoAddress_;
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public Builder setServoAddress(int value) {
        bitField0_ |= 0x00000001;
        servoAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public Builder clearServoAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        servoAddress_ = 0;
        onChanged();
        return this;
      }

      private int angle_ ;
      /**
       * <code>required int32 angle = 2;</code>
       */
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public int getAngle() {
        return angle_;
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public Builder setAngle(int value) {
        bitField0_ |= 0x00000002;
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        angle_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.hitec_proto.SetAngle)
    }

    static {
      defaultInstance = new SetAngle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.hitec_proto.SetAngle)
  }

  public interface SetSameAngleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.hitec_proto.SetSameAngle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getServoAddressesList();
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    int getServoAddressesCount();
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    int getServoAddresses(int index);

    /**
     * <code>required int32 angle = 2;</code>
     */
    boolean hasAngle();
    /**
     * <code>required int32 angle = 2;</code>
     */
    int getAngle();
  }
  /**
   * Protobuf type {@code amber.hitec_proto.SetSameAngle}
   */
  public static final class SetSameAngle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:amber.hitec_proto.SetSameAngle)
      SetSameAngleOrBuilder {
    // Use SetSameAngle.newBuilder() to construct.
    private SetSameAngle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetSameAngle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetSameAngle defaultInstance;
    public static SetSameAngle getDefaultInstance() {
      return defaultInstance;
    }

    public SetSameAngle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetSameAngle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                servoAddresses_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              servoAddresses_.add(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                servoAddresses_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                servoAddresses_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              angle_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = java.util.Collections.unmodifiableList(servoAddresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSameAngle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSameAngle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.Builder.class);
    }

    public static com.google.protobuf.Parser<SetSameAngle> PARSER =
        new com.google.protobuf.AbstractParser<SetSameAngle>() {
      public SetSameAngle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetSameAngle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetSameAngle> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVOADDRESSES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> servoAddresses_;
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getServoAddressesList() {
      return servoAddresses_;
    }
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public int getServoAddressesCount() {
      return servoAddresses_.size();
    }
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public int getServoAddresses(int index) {
      return servoAddresses_.get(index);
    }
    private int servoAddressesMemoizedSerializedSize = -1;

    public static final int ANGLE_FIELD_NUMBER = 2;
    private int angle_;
    /**
     * <code>required int32 angle = 2;</code>
     */
    public boolean hasAngle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 angle = 2;</code>
     */
    public int getAngle() {
      return angle_;
    }

    private void initFields() {
      servoAddresses_ = java.util.Collections.emptyList();
      angle_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAngle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getServoAddressesList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(servoAddressesMemoizedSerializedSize);
      }
      for (int i = 0; i < servoAddresses_.size(); i++) {
        output.writeUInt32NoTag(servoAddresses_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, angle_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < servoAddresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(servoAddresses_.get(i));
        }
        size += dataSize;
        if (!getServoAddressesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        servoAddressesMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, angle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.hitec_proto.SetSameAngle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.hitec_proto.SetSameAngle)
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSameAngle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSameAngle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.Builder.class);
      }

      // Construct using pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servoAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        angle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSameAngle_descriptor;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle getDefaultInstanceForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.getDefaultInstance();
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle build() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle buildPartial() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle result = new pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = java.util.Collections.unmodifiableList(servoAddresses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.servoAddresses_ = servoAddresses_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.angle_ = angle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle) {
          return mergeFrom((pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle other) {
        if (other == pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.getDefaultInstance()) return this;
        if (!other.servoAddresses_.isEmpty()) {
          if (servoAddresses_.isEmpty()) {
            servoAddresses_ = other.servoAddresses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServoAddressesIsMutable();
            servoAddresses_.addAll(other.servoAddresses_);
          }
          onChanged();
        }
        if (other.hasAngle()) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAngle()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> servoAddresses_ = java.util.Collections.emptyList();
      private void ensureServoAddressesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = new java.util.ArrayList<java.lang.Integer>(servoAddresses_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getServoAddressesList() {
        return java.util.Collections.unmodifiableList(servoAddresses_);
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public int getServoAddressesCount() {
        return servoAddresses_.size();
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public int getServoAddresses(int index) {
        return servoAddresses_.get(index);
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder setServoAddresses(
          int index, int value) {
        ensureServoAddressesIsMutable();
        servoAddresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder addServoAddresses(int value) {
        ensureServoAddressesIsMutable();
        servoAddresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder addAllServoAddresses(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureServoAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, servoAddresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder clearServoAddresses() {
        servoAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int angle_ ;
      /**
       * <code>required int32 angle = 2;</code>
       */
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public int getAngle() {
        return angle_;
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public Builder setAngle(int value) {
        bitField0_ |= 0x00000002;
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 angle = 2;</code>
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        angle_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.hitec_proto.SetSameAngle)
    }

    static {
      defaultInstance = new SetSameAngle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.hitec_proto.SetSameAngle)
  }

  public interface SetDifferentAnglesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.hitec_proto.SetDifferentAngles)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getServoAddressesList();
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    int getServoAddressesCount();
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    int getServoAddresses(int index);

    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getAnglesList();
    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    int getAnglesCount();
    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    int getAngles(int index);
  }
  /**
   * Protobuf type {@code amber.hitec_proto.SetDifferentAngles}
   */
  public static final class SetDifferentAngles extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:amber.hitec_proto.SetDifferentAngles)
      SetDifferentAnglesOrBuilder {
    // Use SetDifferentAngles.newBuilder() to construct.
    private SetDifferentAngles(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetDifferentAngles(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetDifferentAngles defaultInstance;
    public static SetDifferentAngles getDefaultInstance() {
      return defaultInstance;
    }

    public SetDifferentAngles getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetDifferentAngles(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                servoAddresses_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              servoAddresses_.add(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                servoAddresses_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                servoAddresses_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                angles_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              angles_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                angles_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                angles_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = java.util.Collections.unmodifiableList(servoAddresses_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          angles_ = java.util.Collections.unmodifiableList(angles_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetDifferentAngles_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetDifferentAngles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.Builder.class);
    }

    public static com.google.protobuf.Parser<SetDifferentAngles> PARSER =
        new com.google.protobuf.AbstractParser<SetDifferentAngles>() {
      public SetDifferentAngles parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetDifferentAngles(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetDifferentAngles> getParserForType() {
      return PARSER;
    }

    public static final int SERVOADDRESSES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> servoAddresses_;
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getServoAddressesList() {
      return servoAddresses_;
    }
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public int getServoAddressesCount() {
      return servoAddresses_.size();
    }
    /**
     * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
     */
    public int getServoAddresses(int index) {
      return servoAddresses_.get(index);
    }
    private int servoAddressesMemoizedSerializedSize = -1;

    public static final int ANGLES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> angles_;
    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getAnglesList() {
      return angles_;
    }
    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    public int getAnglesCount() {
      return angles_.size();
    }
    /**
     * <code>repeated int32 angles = 2 [packed = true];</code>
     */
    public int getAngles(int index) {
      return angles_.get(index);
    }
    private int anglesMemoizedSerializedSize = -1;

    private void initFields() {
      servoAddresses_ = java.util.Collections.emptyList();
      angles_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getServoAddressesList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(servoAddressesMemoizedSerializedSize);
      }
      for (int i = 0; i < servoAddresses_.size(); i++) {
        output.writeUInt32NoTag(servoAddresses_.get(i));
      }
      if (getAnglesList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(anglesMemoizedSerializedSize);
      }
      for (int i = 0; i < angles_.size(); i++) {
        output.writeInt32NoTag(angles_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < servoAddresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(servoAddresses_.get(i));
        }
        size += dataSize;
        if (!getServoAddressesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        servoAddressesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < angles_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(angles_.get(i));
        }
        size += dataSize;
        if (!getAnglesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        anglesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.hitec_proto.SetDifferentAngles}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.hitec_proto.SetDifferentAngles)
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAnglesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetDifferentAngles_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetDifferentAngles_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.Builder.class);
      }

      // Construct using pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servoAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        angles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetDifferentAngles_descriptor;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles getDefaultInstanceForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.getDefaultInstance();
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles build() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles buildPartial() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles result = new pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = java.util.Collections.unmodifiableList(servoAddresses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.servoAddresses_ = servoAddresses_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          angles_ = java.util.Collections.unmodifiableList(angles_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.angles_ = angles_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles) {
          return mergeFrom((pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles other) {
        if (other == pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.getDefaultInstance()) return this;
        if (!other.servoAddresses_.isEmpty()) {
          if (servoAddresses_.isEmpty()) {
            servoAddresses_ = other.servoAddresses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServoAddressesIsMutable();
            servoAddresses_.addAll(other.servoAddresses_);
          }
          onChanged();
        }
        if (!other.angles_.isEmpty()) {
          if (angles_.isEmpty()) {
            angles_ = other.angles_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnglesIsMutable();
            angles_.addAll(other.angles_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> servoAddresses_ = java.util.Collections.emptyList();
      private void ensureServoAddressesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          servoAddresses_ = new java.util.ArrayList<java.lang.Integer>(servoAddresses_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getServoAddressesList() {
        return java.util.Collections.unmodifiableList(servoAddresses_);
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public int getServoAddressesCount() {
        return servoAddresses_.size();
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public int getServoAddresses(int index) {
        return servoAddresses_.get(index);
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder setServoAddresses(
          int index, int value) {
        ensureServoAddressesIsMutable();
        servoAddresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder addServoAddresses(int value) {
        ensureServoAddressesIsMutable();
        servoAddresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder addAllServoAddresses(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureServoAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, servoAddresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 servoAddresses = 1 [packed = true];</code>
       */
      public Builder clearServoAddresses() {
        servoAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> angles_ = java.util.Collections.emptyList();
      private void ensureAnglesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          angles_ = new java.util.ArrayList<java.lang.Integer>(angles_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getAnglesList() {
        return java.util.Collections.unmodifiableList(angles_);
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public int getAnglesCount() {
        return angles_.size();
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public int getAngles(int index) {
        return angles_.get(index);
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public Builder setAngles(
          int index, int value) {
        ensureAnglesIsMutable();
        angles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public Builder addAngles(int value) {
        ensureAnglesIsMutable();
        angles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public Builder addAllAngles(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAnglesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, angles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 angles = 2 [packed = true];</code>
       */
      public Builder clearAngles() {
        angles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.hitec_proto.SetDifferentAngles)
    }

    static {
      defaultInstance = new SetDifferentAngles(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.hitec_proto.SetDifferentAngles)
  }

  public interface SetSpeedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amber.hitec_proto.SetSpeed)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    boolean hasServoAddress();
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    int getServoAddress();

    /**
     * <code>required int32 speed = 2;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 2;</code>
     */
    int getSpeed();
  }
  /**
   * Protobuf type {@code amber.hitec_proto.SetSpeed}
   */
  public static final class SetSpeed extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:amber.hitec_proto.SetSpeed)
      SetSpeedOrBuilder {
    // Use SetSpeed.newBuilder() to construct.
    private SetSpeed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetSpeed(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetSpeed defaultInstance;
    public static SetSpeed getDefaultInstance() {
      return defaultInstance;
    }

    public SetSpeed getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetSpeed(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              servoAddress_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              speed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSpeed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSpeed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.Builder.class);
    }

    public static com.google.protobuf.Parser<SetSpeed> PARSER =
        new com.google.protobuf.AbstractParser<SetSpeed>() {
      public SetSpeed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetSpeed(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetSpeed> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVOADDRESS_FIELD_NUMBER = 1;
    private int servoAddress_;
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    public boolean hasServoAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 servoAddress = 1;</code>
     */
    public int getServoAddress() {
      return servoAddress_;
    }

    public static final int SPEED_FIELD_NUMBER = 2;
    private int speed_;
    /**
     * <code>required int32 speed = 2;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 speed = 2;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    private void initFields() {
      servoAddress_ = 0;
      speed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServoAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, servoAddress_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, speed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, servoAddress_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.hitec_proto.SetSpeed}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amber.hitec_proto.SetSpeed)
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSpeed_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSpeed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.class, pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.Builder.class);
      }

      // Construct using pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        servoAddress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.internal_static_amber_hitec_proto_SetSpeed_descriptor;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed getDefaultInstanceForType() {
        return pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.getDefaultInstance();
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed build() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed buildPartial() {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed result = new pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.servoAddress_ = servoAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed) {
          return mergeFrom((pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed other) {
        if (other == pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.getDefaultInstance()) return this;
        if (other.hasServoAddress()) {
          setServoAddress(other.getServoAddress());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServoAddress()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int servoAddress_ ;
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public boolean hasServoAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public int getServoAddress() {
        return servoAddress_;
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public Builder setServoAddress(int value) {
        bitField0_ |= 0x00000001;
        servoAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 servoAddress = 1;</code>
       */
      public Builder clearServoAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        servoAddress_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>required int32 speed = 2;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000002;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 2;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.hitec_proto.SetSpeed)
    }

    static {
      defaultInstance = new SetSpeed(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.hitec_proto.SetSpeed)
  }

  public static final int SETANGLECOMMAND_FIELD_NUMBER = 70;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle> setAngleCommand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.class,
        pl.edu.agh.amber.hitec.proto.HitecProto.SetAngle.getDefaultInstance());
  public static final int SETSAMEANGLECOMMAND_FIELD_NUMBER = 71;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle> setSameAngleCommand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.class,
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSameAngle.getDefaultInstance());
  public static final int SETDIFFERENTANGLESCOMMAND_FIELD_NUMBER = 72;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles> setDifferentAnglesCommand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.class,
        pl.edu.agh.amber.hitec.proto.HitecProto.SetDifferentAngles.getDefaultInstance());
  public static final int SETSPEEDCOMMAND_FIELD_NUMBER = 73;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed> setSpeedCommand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.class,
        pl.edu.agh.amber.hitec.proto.HitecProto.SetSpeed.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_hitec_proto_SetAngle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_hitec_proto_SetAngle_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_hitec_proto_SetSameAngle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_hitec_proto_SetSameAngle_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_hitec_proto_SetDifferentAngles_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_hitec_proto_SetDifferentAngles_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_hitec_proto_SetSpeed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_hitec_proto_SetSpeed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023modules/hitec.proto\022\021amber.hitec_proto" +
      "\032\017drivermsg.proto\"/\n\010SetAngle\022\024\n\014servoAd" +
      "dress\030\001 \002(\r\022\r\n\005angle\030\002 \002(\005\"9\n\014SetSameAng" +
      "le\022\032\n\016servoAddresses\030\001 \003(\rB\002\020\001\022\r\n\005angle\030" +
      "\002 \002(\005\"D\n\022SetDifferentAngles\022\032\n\016servoAddr" +
      "esses\030\001 \003(\rB\002\020\001\022\022\n\006angles\030\002 \003(\005B\002\020\001\"/\n\010S" +
      "etSpeed\022\024\n\014servoAddress\030\001 \002(\r\022\r\n\005speed\030\002" +
      " \002(\005:F\n\017setAngleCommand\022\020.amber.DriverMs" +
      "g\030F \001(\0132\033.amber.hitec_proto.SetAngle:N\n\023" +
      "setSameAngleCommand\022\020.amber.DriverMsg\030G ",
      "\001(\0132\037.amber.hitec_proto.SetSameAngle:Z\n\031" +
      "setDifferentAnglesCommand\022\020.amber.Driver" +
      "Msg\030H \001(\0132%.amber.hitec_proto.SetDiffere" +
      "ntAngles:F\n\017setSpeedCommand\022\020.amber.Driv" +
      "erMsg\030I \001(\0132\033.amber.hitec_proto.SetSpeed" +
      "B*\n\034pl.edu.agh.amber.hitec.protoB\nHitecP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.agh.amber.common.proto.CommonProto.getDescriptor(),
        }, assigner);
    internal_static_amber_hitec_proto_SetAngle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amber_hitec_proto_SetAngle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_hitec_proto_SetAngle_descriptor,
        new java.lang.String[] { "ServoAddress", "Angle", });
    internal_static_amber_hitec_proto_SetSameAngle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amber_hitec_proto_SetSameAngle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_hitec_proto_SetSameAngle_descriptor,
        new java.lang.String[] { "ServoAddresses", "Angle", });
    internal_static_amber_hitec_proto_SetDifferentAngles_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_amber_hitec_proto_SetDifferentAngles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_hitec_proto_SetDifferentAngles_descriptor,
        new java.lang.String[] { "ServoAddresses", "Angles", });
    internal_static_amber_hitec_proto_SetSpeed_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_amber_hitec_proto_SetSpeed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_amber_hitec_proto_SetSpeed_descriptor,
        new java.lang.String[] { "ServoAddress", "Speed", });
    setAngleCommand.internalInit(descriptor.getExtensions().get(0));
    setSameAngleCommand.internalInit(descriptor.getExtensions().get(1));
    setDifferentAnglesCommand.internalInit(descriptor.getExtensions().get(2));
    setSpeedCommand.internalInit(descriptor.getExtensions().get(3));
    pl.edu.agh.amber.common.proto.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
