// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roboclaw.proto

package pl.edu.agh.amber.roboclaw.proto;

public final class RoboclawProto {
  private RoboclawProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(pl.edu.agh.amber.roboclaw.proto.RoboclawProto.motorsCommand);
    registry.add(pl.edu.agh.amber.roboclaw.proto.RoboclawProto.currentSpeedRequest);
    registry.add(pl.edu.agh.amber.roboclaw.proto.RoboclawProto.currentSpeed);
  }
  public interface MotorsSpeedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 frontLeftSpeed = 1;
    /**
     * <code>optional int32 frontLeftSpeed = 1;</code>
     */
    boolean hasFrontLeftSpeed();
    /**
     * <code>optional int32 frontLeftSpeed = 1;</code>
     */
    int getFrontLeftSpeed();

    // optional int32 frontRightSpeed = 2;
    /**
     * <code>optional int32 frontRightSpeed = 2;</code>
     */
    boolean hasFrontRightSpeed();
    /**
     * <code>optional int32 frontRightSpeed = 2;</code>
     */
    int getFrontRightSpeed();

    // optional int32 rearLeftSpeed = 3;
    /**
     * <code>optional int32 rearLeftSpeed = 3;</code>
     */
    boolean hasRearLeftSpeed();
    /**
     * <code>optional int32 rearLeftSpeed = 3;</code>
     */
    int getRearLeftSpeed();

    // optional int32 rearRightSpeed = 4;
    /**
     * <code>optional int32 rearRightSpeed = 4;</code>
     */
    boolean hasRearRightSpeed();
    /**
     * <code>optional int32 rearRightSpeed = 4;</code>
     */
    int getRearRightSpeed();
  }
  /**
   * Protobuf type {@code amber.roboclaw_proto.MotorsSpeed}
   */
  public static final class MotorsSpeed extends
      com.google.protobuf.GeneratedMessage
      implements MotorsSpeedOrBuilder {
    // Use MotorsSpeed.newBuilder() to construct.
    private MotorsSpeed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MotorsSpeed(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MotorsSpeed defaultInstance;
    public static MotorsSpeed getDefaultInstance() {
      return defaultInstance;
    }

    public MotorsSpeed getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MotorsSpeed(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              frontLeftSpeed_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              frontRightSpeed_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rearLeftSpeed_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rearRightSpeed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsSpeed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.class, pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.Builder.class);
    }

    public static com.google.protobuf.Parser<MotorsSpeed> PARSER =
        new com.google.protobuf.AbstractParser<MotorsSpeed>() {
      public MotorsSpeed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MotorsSpeed(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MotorsSpeed> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 frontLeftSpeed = 1;
    public static final int FRONTLEFTSPEED_FIELD_NUMBER = 1;
    private int frontLeftSpeed_;
    /**
     * <code>optional int32 frontLeftSpeed = 1;</code>
     */
    public boolean hasFrontLeftSpeed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 frontLeftSpeed = 1;</code>
     */
    public int getFrontLeftSpeed() {
      return frontLeftSpeed_;
    }

    // optional int32 frontRightSpeed = 2;
    public static final int FRONTRIGHTSPEED_FIELD_NUMBER = 2;
    private int frontRightSpeed_;
    /**
     * <code>optional int32 frontRightSpeed = 2;</code>
     */
    public boolean hasFrontRightSpeed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 frontRightSpeed = 2;</code>
     */
    public int getFrontRightSpeed() {
      return frontRightSpeed_;
    }

    // optional int32 rearLeftSpeed = 3;
    public static final int REARLEFTSPEED_FIELD_NUMBER = 3;
    private int rearLeftSpeed_;
    /**
     * <code>optional int32 rearLeftSpeed = 3;</code>
     */
    public boolean hasRearLeftSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 rearLeftSpeed = 3;</code>
     */
    public int getRearLeftSpeed() {
      return rearLeftSpeed_;
    }

    // optional int32 rearRightSpeed = 4;
    public static final int REARRIGHTSPEED_FIELD_NUMBER = 4;
    private int rearRightSpeed_;
    /**
     * <code>optional int32 rearRightSpeed = 4;</code>
     */
    public boolean hasRearRightSpeed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 rearRightSpeed = 4;</code>
     */
    public int getRearRightSpeed() {
      return rearRightSpeed_;
    }

    private void initFields() {
      frontLeftSpeed_ = 0;
      frontRightSpeed_ = 0;
      rearLeftSpeed_ = 0;
      rearRightSpeed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, frontLeftSpeed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, frontRightSpeed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rearLeftSpeed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rearRightSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, frontLeftSpeed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, frontRightSpeed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rearLeftSpeed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rearRightSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amber.roboclaw_proto.MotorsSpeed}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsSpeed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.class, pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.Builder.class);
      }

      // Construct using pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frontLeftSpeed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        frontRightSpeed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rearLeftSpeed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        rearRightSpeed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor;
      }

      public pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed getDefaultInstanceForType() {
        return pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.getDefaultInstance();
      }

      public pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed build() {
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed buildPartial() {
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed result = new pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frontLeftSpeed_ = frontLeftSpeed_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.frontRightSpeed_ = frontRightSpeed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rearLeftSpeed_ = rearLeftSpeed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rearRightSpeed_ = rearRightSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed) {
          return mergeFrom((pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed other) {
        if (other == pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.getDefaultInstance()) return this;
        if (other.hasFrontLeftSpeed()) {
          setFrontLeftSpeed(other.getFrontLeftSpeed());
        }
        if (other.hasFrontRightSpeed()) {
          setFrontRightSpeed(other.getFrontRightSpeed());
        }
        if (other.hasRearLeftSpeed()) {
          setRearLeftSpeed(other.getRearLeftSpeed());
        }
        if (other.hasRearRightSpeed()) {
          setRearRightSpeed(other.getRearRightSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 frontLeftSpeed = 1;
      private int frontLeftSpeed_ ;
      /**
       * <code>optional int32 frontLeftSpeed = 1;</code>
       */
      public boolean hasFrontLeftSpeed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 frontLeftSpeed = 1;</code>
       */
      public int getFrontLeftSpeed() {
        return frontLeftSpeed_;
      }
      /**
       * <code>optional int32 frontLeftSpeed = 1;</code>
       */
      public Builder setFrontLeftSpeed(int value) {
        bitField0_ |= 0x00000001;
        frontLeftSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 frontLeftSpeed = 1;</code>
       */
      public Builder clearFrontLeftSpeed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frontLeftSpeed_ = 0;
        onChanged();
        return this;
      }

      // optional int32 frontRightSpeed = 2;
      private int frontRightSpeed_ ;
      /**
       * <code>optional int32 frontRightSpeed = 2;</code>
       */
      public boolean hasFrontRightSpeed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 frontRightSpeed = 2;</code>
       */
      public int getFrontRightSpeed() {
        return frontRightSpeed_;
      }
      /**
       * <code>optional int32 frontRightSpeed = 2;</code>
       */
      public Builder setFrontRightSpeed(int value) {
        bitField0_ |= 0x00000002;
        frontRightSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 frontRightSpeed = 2;</code>
       */
      public Builder clearFrontRightSpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        frontRightSpeed_ = 0;
        onChanged();
        return this;
      }

      // optional int32 rearLeftSpeed = 3;
      private int rearLeftSpeed_ ;
      /**
       * <code>optional int32 rearLeftSpeed = 3;</code>
       */
      public boolean hasRearLeftSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 rearLeftSpeed = 3;</code>
       */
      public int getRearLeftSpeed() {
        return rearLeftSpeed_;
      }
      /**
       * <code>optional int32 rearLeftSpeed = 3;</code>
       */
      public Builder setRearLeftSpeed(int value) {
        bitField0_ |= 0x00000004;
        rearLeftSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rearLeftSpeed = 3;</code>
       */
      public Builder clearRearLeftSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rearLeftSpeed_ = 0;
        onChanged();
        return this;
      }

      // optional int32 rearRightSpeed = 4;
      private int rearRightSpeed_ ;
      /**
       * <code>optional int32 rearRightSpeed = 4;</code>
       */
      public boolean hasRearRightSpeed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 rearRightSpeed = 4;</code>
       */
      public int getRearRightSpeed() {
        return rearRightSpeed_;
      }
      /**
       * <code>optional int32 rearRightSpeed = 4;</code>
       */
      public Builder setRearRightSpeed(int value) {
        bitField0_ |= 0x00000008;
        rearRightSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rearRightSpeed = 4;</code>
       */
      public Builder clearRearRightSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rearRightSpeed_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:amber.roboclaw_proto.MotorsSpeed)
    }

    static {
      defaultInstance = new MotorsSpeed(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:amber.roboclaw_proto.MotorsSpeed)
  }

  public static final int MOTORSCOMMAND_FIELD_NUMBER = 20;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed> motorsCommand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.class,
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.getDefaultInstance());
  public static final int CURRENTSPEEDREQUEST_FIELD_NUMBER = 21;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      java.lang.Boolean> currentSpeedRequest = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int CURRENTSPEED_FIELD_NUMBER = 22;
  /**
   * <code>extend .amber.DriverMsg { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      pl.edu.agh.amber.common.proto.CommonProto.DriverMsg,
      pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed> currentSpeed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.class,
        pl.edu.agh.amber.roboclaw.proto.RoboclawProto.MotorsSpeed.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_roboclaw_proto_MotorsSpeed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016roboclaw.proto\022\024amber.roboclaw_proto\032\017" +
      "drivermsg.proto\"m\n\013MotorsSpeed\022\026\n\016frontL" +
      "eftSpeed\030\001 \001(\005\022\027\n\017frontRightSpeed\030\002 \001(\005\022" +
      "\025\n\rrearLeftSpeed\030\003 \001(\005\022\026\n\016rearRightSpeed" +
      "\030\004 \001(\005:J\n\rmotorsCommand\022\020.amber.DriverMs" +
      "g\030\024 \001(\0132!.amber.roboclaw_proto.MotorsSpe" +
      "ed:-\n\023currentSpeedRequest\022\020.amber.Driver" +
      "Msg\030\025 \001(\010:I\n\014currentSpeed\022\020.amber.Driver" +
      "Msg\030\026 \001(\0132!.amber.roboclaw_proto.MotorsS" +
      "peedB0\n\037pl.edu.agh.amber.roboclaw.protoB",
      "\rRoboclawProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_roboclaw_proto_MotorsSpeed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_roboclaw_proto_MotorsSpeed_descriptor,
              new java.lang.String[] { "FrontLeftSpeed", "FrontRightSpeed", "RearLeftSpeed", "RearRightSpeed", });
          motorsCommand.internalInit(descriptor.getExtensions().get(0));
          currentSpeedRequest.internalInit(descriptor.getExtensions().get(1));
          currentSpeed.internalInit(descriptor.getExtensions().get(2));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pl.edu.agh.amber.common.proto.CommonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
